/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary': '#00344d',
        'surface-bright': '#31394d',
        'secondary-fixed-dim': '#4edea3',
        'on-tertiary': '#1000a9',
        'error': '#ffb4ab',
        'on-secondary-fixed-variant': '#005236',
        'secondary-fixed': '#6ffbbe',
        'inverse-surface': '#dae2fd',
        'outline-variant': '#3e4850',
        'surface-container-low': '#131b2e',
        'on-surface-variant': '#bec8d2',
        'tertiary-container': '#8d90ff',
        'background': '#0b1326',
        'on-primary-fixed': '#001e2f',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004c6e',
        'surface-container-lowest': '#060e20',
        'secondary': '#4edea3',
        'primary-fixed': '#c9e6ff',
        'on-error': '#690005',
        'surface': '#0b1326',
        'on-secondary-fixed': '#002113',
        'on-primary-container': '#003751',
        'secondary-container': '#00a572',
        'surface-dim': '#0b1326',
        'surface-variant': '#2d3449',
        'on-secondary': '#003824',
        'on-tertiary-fixed': '#07006c',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#c0c1ff',
        'surface-tint': '#89ceff',
        'on-secondary-container': '#00311f',
        'surface-container-highest': '#2d3449',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#006591',
        'surface-container': '#171f33',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'tertiary-fixed': '#e1e0ff',
        'on-background': '#dae2fd',
        'surface-container-high': '#222a3d',
        'tertiary': '#c0c1ff',
        'primary-container': '#0ea5e9',
        'primary': '#89ceff',
        'on-surface': '#dae2fd',
        'outline': '#88929b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        'body-base': ['Inter', 'system-ui', 'sans-serif'],
        'mono-label': ['Space Grotesk', 'monospace'],
        'terminal': ['Fira Code', 'Consolas', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm':    ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'terminal':   ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-base':  ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg':['30px', { lineHeight: '1.2', fontWeight: '600' }],
        'mono-label': ['12px', { lineHeight: '1',   letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md':['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
